apiVersion: v1
kind: Service   
metadata:
  name: frontend-network-service
  namespace: app-demo
selector:
  type: NodePort
  spec:
    selector:
      app: frontend
    ports:
      - port: 80
        targetPort: 80