apiVersion: v1
kind: Service
metadata:
  name: demo-app-mysql-network-service
  namespace: app-demo 
selector:
  type: ClusterIP
  app: demo-app-mysql
  ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306